# Generated by Django 3.0.8 on 2020-07-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
